# .circleci/config.yml

# Specify the config version - version 2 is latest.
version: 2
 
# # Define the jobs for the current project.
jobs:
  build:
    # Specify the Xcode version to use.
    macos:
      xcode: "9.1.0"
    
    # docker:
    #   - image: circleci/ruby:2.4-node

    # Define the steps required to build the project.
    steps:

      # Get the code from the VCS provider.
      - checkout

       # Restore bundle cache
      - type: cache-restore
        name: Restore bundle cache
        key: rails-demo-bundle-{{ checksum "Gemfile.lock" }}

      - run:
          name: Bundle update 
          command: bundle update #--path vendor/bundle 

      # Store bundle cache
      - type: cache-save
        name: Store bundle cache
        key: rails-demo-bundle-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle


      # - run: bundle update 
     
        # Download CocoaPods specs via HTTPS (faster than Git)
        # and install CocoaPods.
        # - run:
        #     name: Install CocoaPods
        #     command: |
        #       curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
        #       pod install

      # Run tests.
      - run:
          name: Run tests
          command: bundle exec fastlane test
        post:
           - bundle exec slather

      - store_test_results:
          path: ~/Library/test_output/report.junit
      - store_artifacts:
          path: ~/Library/test_output/test-results
          # Destination is the name of the item in the Artifacts tab
          # that will contain the paths specified in this step.
          destination: scan-test-results
      - store_artifacts:
          path: ~/Library/Logs/scan
          destination: scan-logs