version: 2
jobs:
build:
  macos:
    xcode: "9.1.0" 
    steps: 
      - checkout
      - run:
         name: Bundle update 
        command: bundle update 
      - run:
        name: Run tests
        command: bundle exec fastlane test
deploy:
  macos:
    xcode: "9.1.0"
    steps: 
      - checkout
      - run:
         name: Bundle update 
         command: bundle update
      - run:
         name: Run Deployments 
         command: bundle exec fastlane scan

workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
              branches:
                 only: newBrach