# .circleci/config.yml

# Specify the config version - version 2 is latest.
version: 2
 
# # Define the jobs for the current project.
jobs:
  build:
    # Specify the Xcode version to use.
    macos:
      xcode: "9.1.0"
    
    # docker:
    #   - image: circleci/ruby:2.4-node

    # Define the steps required to build the project.
    steps:

      # Get the code from the VCS provider.
      - checkout
      - restore_cache:
          keys:
          - v1-gems-{{ checksum "Gemfile.lock" }}
          # Fall back to using the latest cache if no exact match is found.
          - v1-gems-
      # Install gems.
      - run:
          name: Bundle install
          command: bundle check || bundle update
          environment:
            BUNDLE_JOBS: 4
            BUNDLE_RETRY: 3
            # This is the path where all the gems will be installed, and
            # which CircleCI will later cache.
            BUNDLE_PATH: vendor/bundle
      - save_cache:
          key: v1-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
     
        # Download CocoaPods specs via HTTPS (faster than Git)
        # and install CocoaPods.
        # - run:
        #     name: Install CocoaPods
        #     command: |
        #       curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
        #       pod install

      # Run tests.
      - run:
          name: Run tests
          command: bundle exec fastlane test