# .circleci/config.yml

# Specify the config version - version 2 is latest.
 version: 2
 
# # Define the jobs for the current project.
# no. 1 job is to 
  jobs:

    build:
      macos:
       xcode: "9.1.0"
     steps:
      # Get the code from the VCS provider.
       - checkout

       # Restore bundle cache
       - type: cache-restore
          name: Restore bundle cache
           key: rails-demo-bundle-{{ checksum "Gemfile.lock" }}

       - run:
          name: Bundle update 
          command: bundle update # --path vendor/bundle 

      # Store bundle cache
      - type: cache-save
        name: Store bundle cache
        key: rails-demo-bundle-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      # Run tests.
      - run:
          name: Run tests
          command: bundle exec fastlane test
          #post: - bundle exec slather

# no. 2 job is to deployment
    deploy:
    # Specify the Xcode version to use.
      macos:
        xcode: "9.1.0"
      steps:

      # Get the code from the VCS provider.
       - checkout
       - run:
            name: Bundle update 
            command: bundle update # --path vendor/bundle 

      # Run tests.
        - run:
            name: Run Deployments 
           command: bundle exec fastlane test
          #post: - bundle exec slather

workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build
      - deploy:
          requires:
             - build
           filters:
              branches:
                only: master