version: 2
jobs: 
  build: 
    deploy: 
      macos: 
        xcode: "9.1.0"
    macos: 
      xcode: "9.0"
    steps: 
      - checkout
      - 
        key: "rails-demo-bundle-{{ checksum \"Gemfile.lock\" }}"
        name: "Restore bundle cache"
        type: cache-restore
      - 
        command: "bundle update"
        name: "Bundle update"
        run: ~
      - 
        key: "rails-demo-bundle-{{ checksum \"Gemfile.lock\" }}"
        name: "Store bundle cache"
        paths: 
          - vendor/bundle
        type: cache-save
      - 
        run: 
          command: "bundle exec fastlane test"
          name: "Run tests"
version: 2
workflows: 
  build-n-deploy: 
    jobs: 
      - build
      - 
        deploy: 
          filters: 
            branches: 
              only: master
          requires: 
            - build